version: "3.9"

services:
  djangoapp:
    container_name: spekter
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - sqlite3

  sqlite3:
    image: keinos/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

volumes:
  spekter:
